document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="css/enhancements.css"><link rel="stylesheet" href="css/result-clickable.css">');
const teams=leagueTeamCatalog.map(team=>[team.zh,team.name,team.code,0,0,0,0,0,0,0,'',team.pot]);
const verifiedQualificationMatches=(typeof qualificationResults==='undefined'?[]:qualificationResults.map(m=>[m[0],m[3],m[4],`${m[5]}-${m[6]}`,'—','qualifying']));
const initialMatchMap=new Map([...rawMatches,...verifiedQualificationMatches].map(m=>{const row=[m[0],canonicalTeamName(m[1]),canonicalTeamName(m[2]),m[3],m[4],m[5]];return [row.slice(0,3).join('|'),row]}));
const matches=[...initialMatchMap.values()].sort((a,b)=>b[0].localeCompare(a[0]));
document.documentElement.dataset.staticVerified='2026-08-26';
const display=n=>String(n).includes(' / ')?`${n.split(' / ').map(team=>teamChineseName(team)).join(' / ')}（${n.split(' / ').map(team=>canonicalTeamName(team)).join(' / ')}）`:`${teamChineseName(n)}（${canonicalTeamName(n)}）`;
const tbody=document.querySelector('#standings');
function render(q=''){tbody.innerHTML=teams.map((t,i)=>({t,i})).filter(({t})=>(t[0]+t[1]).toLowerCase().includes(q.toLowerCase())).map(({t,i})=>`<tr class="rank r${i+1} pot-${t[11]}" data-team="${t[1]}" tabindex="0" aria-label="查看${t[0]}详情"><td>${i+1}</td><td class="team"><i class="badge">${t[2]}</i><span class="bilingual"><strong>${t[0]}</strong><small>${t[1]}</small></span><em class="pot-chip">第${t[11]}档</em></td><td>${t[3]}</td><td>${t[4]}</td><td>${t[5]}</td><td>${t[6]}</td><td>${t[7]}–${t[8]}</td><td>${t[7]-t[8]>0?'+':''}${t[7]-t[8]}</td><td class="pts">${t[9]}</td><td><span class="form">${[...t[10]].map(x=>`<i class="${x.toLowerCase()}">${x==='W'?'胜':x==='D'?'平':'负'}</i>`).join('')||'—'}</span></td></tr>`).join('');}
render();document.querySelector('#search').oninput=e=>render(e.target.value);
function renderResults(){const latest=matches.slice(0,8),grid=document.querySelector('#resultGrid');grid.innerHTML=latest.map(m=>`<div class="match" role="button" tabindex="0" data-date="${m[0]}" data-home="${encodeURIComponent(m[1])}" data-away="${encodeURIComponent(m[2])}"><time>${m[0].slice(5).replace('-',' / ')}</time><p><span>${display(m[1])}</span><b>${m[3]}</b><span>${display(m[2])}</span></p><small>半场 ${m[4]}　·　全场 ${m[3]}</small><span class="match-detail-cue">查看详细信息 →</span></div>`).join('');grid.querySelectorAll('.match').forEach(card=>{const open=()=>window.openFixtureDetail?.(decodeURIComponent(card.dataset.home),decodeURIComponent(card.dataset.away),card.dataset.date,'');card.onclick=open;card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}});document.querySelector('.hero-stat b').textContent=matches.length;}
renderResults();
const drawer=document.querySelector('#drawer'),overlay=document.querySelector('#overlay');
function close(){drawer.classList.remove('open');overlay.classList.remove('open');if(location.hash.startsWith('#team='))history.replaceState(null,'',location.pathname+location.search)}document.querySelector('#close').onclick=close;overlay.onclick=close;document.querySelector('#latestBtn').onclick=()=>document.querySelector('#latest').scrollIntoView({behavior:'smooth'});
